name: Build and Push Python Image to GoogleCloud Platform
on:
    push:
        branches: [ master ]
jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: flask-cicd-demo
            PROJECT_ID: prompta-alpha-one
        steps:
        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2.1.0

        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v2.1.0
          with:
            credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            project_id: ${{ env.PROJECT_ID }}

        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME:latest .

        - name: Configure Docker Client
          run: |-
            gcloud auth configure-docker --quiet
            

        - name: Push Docker Image to Container Registry (GCR)
          env:
            GIT_TAG: v0.1.0
          run: |-
              docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
              docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
              docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
              docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
