name: Build and Push Python Image to GoogleCloud Platform
on:
    push:
        branches: [ master ]
jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: flask-cicd-demo
            PROJECT_ID: prompta-alpha-one
        steps:
        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2.1.0

        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v2.1.0
          with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'

        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME:latest .

        - name: Automatic Tagging of Releases
          id: increment-git-tag
          run: |
            bash ./scripts/git_update.sh -v patch

        - name: Configure Docker Client
          run: |-
            gcloud auth configure-docker --quiet
            gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev --quiet
            
        - name: Push Docker Image to Artifact Registry
          env:
            GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          run: |-
              docker tag $IMAGE_NAME:latest northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
              docker tag $IMAGE_NAME:latest northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
              docker push northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
              docker push northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

        - name: Deploy to App Engine
          env:
            GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          run: |
            echo "GIT_TAG=$GIT_TAG"
            gcloud app deploy --image-url=northamerica-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/images/$IMAGE_NAME:$GIT_TAG --quiet
